services:
  - type: web
    name: saas-employee-management
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node debug-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://saas-employee-management.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true 